//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolEMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public int id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string confirmPassword { get; set; }
        public string schoolName { get; set; }
        public string schoolAddress { get; set; }
        public string mobile { get; set; }
    }
}
