//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolEMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int id { get; set; }
        public int parentId { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public System.DateTime birthdate { get; set; }
        public int genderId { get; set; }
        public string address { get; set; }
        public int age { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Parent Parent { get; set; }
    }
}
