//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolEMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int id { get; set; }
        public int semesterId { get; set; }
        public int courseId { get; set; }
        public string taskName { get; set; }
        public string taskDetails { get; set; }
        public string taskFile { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Semester Semester { get; set; }
    }
}
